<a href="https://colab.research.google.com/github/Gurpreetsr/QXI_DataScience_Gurpreet/blob/main/NumpyPanda_Assign_2_241020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1 Product
import numpy as np
a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])
z = np.prod([a1,a2])
print(z)



40320


In [ ]:
# 2 GCD
n1 = 4
n2 = 8
x = np.gcd(n1, n2)
print(x)


4


In [ ]:
# 3 Power
n1 = np.array([10, 15, 20])
n2 = np.array([1, 2, 3])
p = np.power(n1, n2)
print(p)

[  10  225 8000]


In [ ]:
# 4 LCM 
s = np.arange(2,12)
y = np.lcm.reduce(s)
print(y)


27720


In [ ]:
# 5 Sin
y = np.sin(np.pi/4)
print(y)

0.7071067811865475


In [ ]:
# 6 Slicing Step
step = np.array([1, 2, 3, 4, 5, 6, 7])
print(step[1:5:2])

[2 4]


In [ ]:
 # 7 Copy 
 x = np.array([1, 2, 3, 4, 5]) 
 y = x.copy()
 x[3] = 100
 print(x)

[  1   2   3 100   5]


In [ ]:
# 8 Split
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Output = np.array_split(x,4)
print(Output)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:

# 9 Searchsort
x = np.array([ 1,2,6,9])
x =np.searchsorted(x,2)
print(x)

1


In [ ]:
# 10 Search left
s = np.array([2,3,4,5])
x = np.searchsorted(s,3,side='Left')
print(x)

1


In [ ]:
# 11 Permutation
from numpy import random
x = np.array([1,2,3,4,5])
print(random.permutation(x))

[5 4 1 3 2]


In [ ]:
# 12 Future value period = 10 yrs,diffrent interest rate =5%,6%,7%
x = np.array((0.05,0.06,0.07))/12
np.fv(x,10*12,-100,-150)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: numpy.fv is deprecated and will be removed from NumPy 1.20. Use numpy_financial.fv instead (https://pypi.org/project/numpy-financial/).
  This is separate from the ipykernel package so we can avoid doing imports until


array([15775.27936922, 16660.84419075, 17609.92994986])

In [ ]:
#13 Period of Payment  Payment/month = 200,Loan = 10000,int = 6%
np.nper(0.06/12,-200,10000)




/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: numpy.nper is deprecated and will be removed from NumPy 1.20. Use numpy_financial.nper instead (https://pypi.org/project/numpy-financial/).
  


array(57.68013596)

In [ ]:
#14 View
x = np.array([1,2,3,4,5])
y = x.view()
x[2] = 52
print(x)

[ 1  2 52  4  5]


In [ ]:
#15 Choice
a = random.choice([1,2,3,4],p=[0.1,0.3,0.2,0.4],size=(10))
print(a)

[2 4 4 1 4 4 2 4 3 4]


In [ ]:
#16  Normal Distribution
from numpy import random
d = random.normal(size=(2,3))
print (d)

[[ 0.10100981 -1.10886447 -1.17495556]
 [-0.52614461  0.62172917 -0.4864516 ]]


PANDA

In [ ]:
# 1 1D Array
import pandas as pd
ds = pd.Series([2,4,6,8,10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [ ]:
#2 Cumulative Mul

x = [2, 10, np.nan, 4, 3, 0, 1]
series = pd.Series(x)
cumprod = series.cumprod() 
cumprod

0      2.0
1     20.0
2      NaN
3     80.0
4    240.0
5      0.0
6      0.0
dtype: float64

In [ ]:
#3 Markdown
# import pandas 
import pandas as pd 
  
df = pd.DataFrame({"A": [1, 2, 3], 
                   "B": [1.3, 2.6, 3.9]},  
                    index =['a', 'b', 'c'])
c = df.to_markdown()
print(c)

|    |   A |   B |
|:---|----:|----:|
| a  |   1 | 1.3 |
| b  |   2 | 2.6 |
| c  |   3 | 3.9 |


In [ ]:
# 4 Factorial
def facto(num): 
    if num == 2: 
        return 2
    else: 
        return num * facto(num-1) 
          print(facto(3)) 

6


In [ ]:
# 5 Upper ()
string = 'ABCDEF'
print(string.isupper())


True


In [ ]:
# 6 Date series
import pandas as pd
dates = pd.Series(pd.date_range('2020-12-01',periods=31, freq='D'))
print(dates)

0    2020-12-01
1    2020-12-02
2    2020-12-03
3    2020-12-04
4    2020-12-05
5    2020-12-06
6    2020-12-07
7    2020-12-08
8    2020-12-09
9    2020-12-10
10   2020-12-11
11   2020-12-12
12   2020-12-13
13   2020-12-14
14   2020-12-15
15   2020-12-16
16   2020-12-17
17   2020-12-18
18   2020-12-19
19   2020-12-20
20   2020-12-21
21   2020-12-22
22   2020-12-23
23   2020-12-24
24   2020-12-25
25   2020-12-26
26   2020-12-27
27   2020-12-28
28   2020-12-29
29   2020-12-30
30   2020-12-31
dtype: datetime64[ns]


In [ ]:
#7 Timestamp
import pandas as pd
x = pd.Timestamp('2020-02-07')

print(x)

2020-02-07 00:00:00


In [ ]:
#8 Max row
import pandas as pd
pd.options.display.max_rows

60

In [ ]:
# 9 Cut

In [ ]:
pd.cut(np.array([1,7,5,4,6,3]),3)

[(0.994, 3.0], (5.0, 7.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (0.994, 3.0]]
Categories (3, interval[float64]): [(0.994, 3.0] < (3.0, 5.0] < (5.0, 7.0]]

In [ ]:
# 10 Numeric conversion
s = pd.Series(['1.0','2',-3])
pd.to_numeric(s)

0    1.0
1    2.0
2   -3.0
dtype: float64

In [ ]:
#11 Roll count
s = pd.Series([2,3,np.nan,10])
s.rolling(2).count()

0    1.0
1    2.0
2    1.0
3    1.0
dtype: float64

In [ ]:
#12 Duplicates
idx = pd.Index([1,5,7,7])
idx.has_duplicates

True

In [ ]:
# 13 Index argmin
s = pd.Series({'A':50,'B':70,'C':80,'D':150,"E":25})
s



A     50
B     70
C     80
D    150
E     25
dtype: int64

In [ ]:
s.argmin

<bound method IndexOpsMixin.argmin of A     50
B     70
C     80
D    150
E     25
dtype: int64>

In [ ]:
idx1 = pd.Index([1,2,3,4])
idx2 = pd.Index([3,4,5,6])
idx1.union(idx2)


Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')